name: Deploy Kestra Dashboard with Ngrok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          # Update package lists and install curl & jq (for API response)
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install Ngrok
        run: |
          # Install Ngrok
          sudo apt-get install -y ngrok

      - name: Run Kestra Locally
        run: |
          # Assuming you have Docker installed to run Kestra locally
          # Or you can run Kestra using other methods if preferred
          # Running Kestra locally in Docker (if this is your setup)
          docker run -d -p 8080:8080 kestra/kestra:latest

      - name: Expose Kestra with Ngrok
        run: |
          # Expose the local Kestra service running on port 8080 using Ngrok
          ngrok http 8080 &
          sleep 10  # Wait for Ngrok to establish the tunnel

      - name: Output Ngrok URL
        run: |
          # Output the public URL of the exposed service
          echo "Ngrok URL: $(curl --silent --show-error http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"
