name: Deploy Kestra Instance

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install Kestra CLI
      run: |
        curl -L https://github.com/kestra-io/kestra/releases/download/v0.3.0/kestra-cli-0.3.0-linux-amd64.tar.gz -o kestra-cli.tar.gz
        tar -xzf kestra-cli.tar.gz
        sudo mv kestra /usr/local/bin/kestra

    - name: Deploy Kestra Dashboard
      run: |
        kestra server start --config dashboard/dashboard-config.yaml
        kestra workflows deploy --config dashboard/kestra-workflows.yaml

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dashboard